/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business_Logic.palyaFelepitese;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Cellár László
 *
 * Létrehozzuk a mezőként szolgáló gombokat és betöltjük a létrehozott pályát.
 *
 */
public class jatek extends javax.swing.JFrame implements ActionListener {

    JButton[][] mezo;
    int PalyaMerete, SzamokMeddig;
    palyaFelepitese pf;

    /**
     *
     * @author Cellár László
     *
     * A konstruktoron keresztül kapott értékekből meghatározzuk és létrehozzuk
     * a pálya méretét, elmentjük, hogy meddig lehet menni a számokkal, illetve
     * betöltjük a pályát, amelyet már létrehoztunk.
     * @param inputPalyaMerete A pálya méretét jelzi.
     * @param inputSzamokMeddig Azt mutatja, hogy meddig használhatunk fel számokat a játék során.
     * @param palyafelepitese A létrehozott pályát tárolja.
     *
     */
    public jatek(int inputPalyaMerete, int inputSzamokMeddig, palyaFelepitese palyafelepitese) {
        initComponents();
        PalyaMerete = inputPalyaMerete;
        SzamokMeddig = inputSzamokMeddig;
        mezo = new JButton[PalyaMerete + 1][PalyaMerete + 1];
        this.pf = palyafelepitese;
        palyabetoltese();
    }

    /**
     *
     * @author Cellár László
     *
     * Itt töljük be a pályát, amelyet már létrehozunk. Megalkotjuk a mezőként
     * funkcionáló gombokat, valamint betöltjük rájuk a megfelelő tartalmakat. A
     * pályaszerkesztő során létrehozott gombok használhatóságát letiltjuk.
     *
     */
    public void palyabetoltese() {
        palya.setLayout(new GridLayout(PalyaMerete, PalyaMerete, 5, 5));
        palya.setVisible(true);
        gombok.setLayout(new GridLayout(1, 2));
        gombok.setVisible(true);

        for (int n = 0; n < PalyaMerete; n++) {
            for (int n2 = 0; n2 < PalyaMerete; n2++) {

                mezo[n][n2] = new JButton();

                mezo[n][n2].setText(pf.ertekLekerdezes(n, n2));
                mezo[n][n2].setFocusable(false);
                mezo[n][n2].setFont(new Font("Arial Black", Font.PLAIN, 22));
                mezo[n][n2].addActionListener(this);
                mezo[n][n2].setPreferredSize(new Dimension(40, 40));
                palya.add(mezo[n][n2]);

                if ((!(mezo[n][n2].getText().equalsIgnoreCase("↑"))) && (!(mezo[n][n2].getText().equalsIgnoreCase("↓"))) && (!(mezo[n][n2].getText().equalsIgnoreCase("→"))) && (!(mezo[n][n2].getText().equalsIgnoreCase("←"))) && (!(mezo[n][n2].getText().equalsIgnoreCase("")))) {
                    mezo[n][n2].setEnabled(false);
                }

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palya = new javax.swing.JPanel();
        gombok = new javax.swing.JPanel();
        kilepes = new javax.swing.JButton();
        ellenorzes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bűvös csiga játék");
        setPreferredSize(new java.awt.Dimension(453, 484));

        palya.setMinimumSize(new java.awt.Dimension(300, 300));
        palya.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout palyaLayout = new javax.swing.GroupLayout(palya);
        palya.setLayout(palyaLayout);
        palyaLayout.setHorizontalGroup(
            palyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        palyaLayout.setVerticalGroup(
            palyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        kilepes.setText("Kilépés");
        kilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilepesActionPerformed(evt);
            }
        });

        ellenorzes.setText("Ellenőrzés");
        ellenorzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellenorzesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gombokLayout = new javax.swing.GroupLayout(gombok);
        gombok.setLayout(gombokLayout);
        gombokLayout.setHorizontalGroup(
            gombokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gombokLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(kilepes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ellenorzes)
                .addGap(50, 50, 50))
        );
        gombokLayout.setVerticalGroup(
            gombokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gombokLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(gombokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilepes)
                    .addComponent(ellenorzes)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bűvös csiga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gombok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(palya, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(palya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(gombok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ellenorzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellenorzesActionPerformed

        /**
         * @author Szőllősi Viktor
         *
         * Megvizsgáljuk, hogy a pálya helyesen van-e kitöltve, ha igen, akkor
         * átugrunk az eredményt kijelző JFrame-re.
         *
         */
        try {

            pf.palyaKorkoros(PalyaMerete, 0, 0);

            if (pf.palyaJo() == true && pf.folytonosE() == true) {
                dispose();
                eredmeny e = new eredmeny();

                e.setVisible(true);

            } else {
                showMessageDialog(null, "Egy sorban és oszlopban csak egyszer szerepeljen egy szám. Továbbá a számok növekvő sorrendben kövessék egymást.", "Hiba", ERROR_MESSAGE);
            }

        } catch (NumberFormatException nfe) {
            showMessageDialog(null, "Hibába ütköztem.", "Hiba", ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ellenorzesActionPerformed

    private void kilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilepesActionPerformed

        /**
         *
         * @author Szőllősi Viktor
         *
         * Lehetővé teszi a játékból való kilépést.
         *
         */
        this.dispose();

    }//GEN-LAST:event_kilepesActionPerformed

    /**
     *
     * @author Cellár László
     *
     * Vizsgálja a kattintásokat és minden egyes mezőn történő változtatást
     * eltárol az adatszerkezetben, illetve frissíti a gombon megjelenő
     * szöveget.
     *
     */
    public void actionPerformed(ActionEvent e) {

        for (int i = 0; i < PalyaMerete; i++) {
            for (int j = 0; j < PalyaMerete; j++) {
                if (e.getSource() == mezo[i][j]) {
                    if (mezo[i][j].getText().equalsIgnoreCase("↑") || mezo[i][j].getText().equalsIgnoreCase("↓") || mezo[i][j].getText().equalsIgnoreCase("→") || mezo[i][j].getText().equalsIgnoreCase("←") || mezo[i][j].getText().equalsIgnoreCase("")) {
                        mezo[i][j].setText("1");
                        pf.ertekHozzaadas(i, j, Integer.parseInt(mezo[i][j].getText()));
                    } else if (Integer.parseInt(mezo[i][j].getText()) < SzamokMeddig) {
                        mezo[i][j].setText(String.valueOf(Integer.parseInt(mezo[i][j].getText()) + 1));
                        pf.ertekHozzaadas(i, j, Integer.parseInt(mezo[i][j].getText()));
                    } else {
                        mezo[i][j].setText(pf.nyil(i, j));
                        pf.ertekHozzaadas(i, j, 0);
                    }

                }

            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ellenorzes;
    private javax.swing.JPanel gombok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kilepes;
    private javax.swing.JPanel palya;
    // End of variables declaration//GEN-END:variables
}
