/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cellar-PC
 */




public class palya_szerkeszto extends javax.swing.JFrame {
    
    
    
    public palya_szerkeszto(int PalyaMerete, int SzamokMeddig) {
        
        initComponents();
        palya_letrehozas(PalyaMerete, SzamokMeddig);


    }
    
    
    private void palya_letrehozas(int PalyaMerete, int SzamokMeddig)
    {
        
        this.getContentPane().setLayout(new GridLayout(PalyaMerete, PalyaMerete));

        for (int n=0; n<PalyaMerete; n++)
        {
          for (int n2=0; n2<PalyaMerete; n2++)
        {
            
            JButton[][] mezo = new JButton[PalyaMerete][PalyaMerete];
            mezo[n][n2] = new JButton();
            mezo[n][n2].setText("");
            mezo[n][n2].setFont(new Font("Arial Black", Font.PLAIN, 22));
                             mezo[n][n2].addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent lehetosegek) {
                        ButtonActionPerformed(lehetosegek, SzamokMeddig);
                    }

                });
            mezo[n][n2].setPreferredSize(new Dimension(40, 40));
            add(mezo[n][n2]);
           
        }  
          
        }
    }
    
    
    
        private void ButtonActionPerformed(ActionEvent lehetosegek, int SzamokMeddig) {
        JButton aktualis_mezo = (JButton) (lehetosegek.getSource());
        if (aktualis_mezo.getText()=="") aktualis_mezo.setText("1");
        else if (Integer.parseInt(aktualis_mezo.getText())<SzamokMeddig) aktualis_mezo.setText(String.valueOf(Integer.parseInt(aktualis_mezo.getText())+1));
        else aktualis_mezo.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
